//Login
export const ON_LOGGING = 'ON_LOGGING'
export const UPDATE_LOGIN_PHONENUMBER = 'UPDATE_LOGIN_PHONENUMBER'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_STORE = 'UPDATE_STORE'
export const UPDATE_REGISTER_STORENAME = 'UPDATE_REGISTER_STORENAME'


//Mode
export const UPDATE_VERIFICATION_PASSWORD = 'UPDATE_VERIFICATION_PASSWORD'
export const UPDATE_VERIFICATION = 'UPDATE_VERIFICATION'
export const UPDATE_VERIFICATIONREQUIRED = 'UPDATE_VERIFICATIONREQUIRED'

//Register
export const UPDATE_REGISTER_PHONENUMBER = 'UPDATE_REGISTER_PHONENUMBER'
export const UPDATE_REGISTER_FIRSTNAME = 'UPDATE_REGISTER_FIRSTNAME'
export const UPDATE_REGISTER_LASTNAME = 'UPDATE_REGISTER_LASTNAME'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'
export const UPDATE_REGISTER_PASSWORDCONFIRM = 'UPDATE_REGISTER_PASSWORDCONFIRM'

//Home
export const ON_RESERVATION = 'ON_RESERVATION'
export const UPDATE_WAITLIST_PHONENUMBER = 'UPDATE_WAITLIST_PHONENUMBER'
export const UPDATE_CHECKIN_PHONENUMBER = 'UPDATE_CHECKIN_PHONENUMBER'
export const UPDATE_HOME_CUSTOMERNAME = 'UPDATE_HOME_CUSTOMERNAME'
export const UPDATE_HOME_SEATS = 'UPDATE_HOME_SEATS'
export const UPDATE_SIDE_BANNER = 'UPDATE_SIDE_BANNER'
export const UPDATE_SUBSCRIPTIONSWITCH = 'UPDATE_SUBSCRIPTIONSWITCH'

//Profile
export const UPDATE_PROFILE_VERIFICATION = 'UPDATE_PROFILE_VERIFICATION'
export const UPDATE_PROFILE_STORENAME = 'UPDATE_PROFILE_STORENAME'
export const UPDATE_PROFILE_ESTMIN = 'UPDATE_PROFILE_ESTMIN'
export const UPDATE_PROFILE_PASSWORD = 'UPDATE_PROFILE_PASSWORD'


//Analytic
export const UPDATE_ANALYTIC_CHART = 'UPDATE_ANALYTIC_CHART'

//Megaphone
export const ON_MEGAPHONE = 'ON_MEGAPHONE'
export const UPDATE_MEGAPHONE_CONTENT = 'UPDATE_MEGAPHONE_CONTENT'
export const UPDATE_MEGAPHONE_TARGETNUMBER = 'UPDATE_MEGAPHONE_TARGETNUMBER'

//Loyal
export const UPDATE_LOYAL_PHONENUMBER = 'UPDATE_LOYAL_PHONENUMBER'
export const UPDATE_LOYALREWARD = 'UPDATE_LOYALREWARD'
export const UPDATE_RECENTBIGWINNERS = 'UPDATE_RECENTBIGWINNERS'
export const UPDATE_RECENTREWARDSRECEIVERS = 'UPDATE_RECENTREWARDSRECEIVERS'
export const UPDATE_LOYAL_NEWREWARD = 'UPDATE_LOYAL_NEWREWARD'
export const UPDATE_LOYAL_POINTREQUIRED = 'UPDATE_LOYAL_POINTREQUIRED'
export const UPDATE_LOYAL_NEWBIGWINNING = 'UPDATE_LOYAL_NEWBIGWINNING'
export const UPDATE_LOYAL_ODDS = 'UPDATE_LOYAL_ODDS'
export const UPDATE_LOYAL_SEARCHRESULT = 'UPDATE_LOYAL_SEARCHRESULT'
export const UPDATE_LOYAL_MAINMESSAGE = 'UPDATE_LOYAL_MAINMESSAGE'
export const UPDATE_LOYAL_EXTRAPOINT = 'UPDATE_LOYAL_EXTRAPOINT'


//local IP
export const LOCAL_IP = 'https://www.columbusapi.com';
//'http://35.160.207.253:8081'
//'https://www.chirpapi.com:8081';
//'http://192.168.0.5:8080';
// export const LOCAL_IP = '54.218.16.211:8081';
//'192.168.0.4:8080';
//'54.218.16.211:8081';
//'172.20.10.4:8080'
//'54.218.16.211:8081'
//'10.0.1.102'
